### ISSUE TITLE
Have a fallback default charm icon when none is found.

### ISSUE THREAD

**Issue by marcoceppi** [juju/jujusvg#22]
I attempted to implement this but ended up driving the generation time up linearly. After an attempt to refactor to use go routines I promptly gave up. Here is the linear implementation and an example of what it generates:

```golang
func iconURL(ref *charm.Reference) string {
    url := "https://api.jujucharms.com/v4/" + ref.Path() + "/archive/icon.svg"
    resp, err := http.Head(url)
    if err != nil {
        log.Fatalf("err %s\n", err);
    }

    if resp.StatusCode == 404 {
        url = "https://jujucharms.com/static/img/icons/default-charm.svg"
    }

    return url
}
```

http://svg.juju.solutions/?bundle-file=https://raw.githubusercontent.com/whitmo/bundle-kubernetes/master/bundles.yaml

Not sure if having the charmstore API return default-charm icon would be a better place to have this logic @mitechie ?

**Comment by makyo** [comment]
@marcoceppi the logic used to live in Charmworld, as you suggested, but hasn't been implemented in the store yet.  #23 provides a default HTTP fetcher for icons, which allows concurrent access.  I'll look into adding this functionality as a follow-up branch.

**Comment by makyo** [comment]
@marcoceppi #26 implements this for embedded icons, but not for linked icons (convention disallows HTTP access on that implementation of `IconFetcher`).  Hopefully this helps cover the use case of providing a default icon for embedding in bundle diagrams

**Comment by makyo** [comment]
@marcoceppi I've been corrected by @rogpeppe, the store *does* return the default icon if none exists, but only if accessed via the `/icon.svg` API endpoint, which is smarter about non-existent icons.  The `/archive/icon.svg` endpoint correctly 404s if that file does not exist in the path.  See https://api.jujucharms.com/v4/trusty/percona-cluster-18/icon.svg vs https://api.jujucharms.com/v4/trusty/percona-cluster-18/archive/icon.svg

**Comment by marcoceppi** [comment]
Oh, this is amazing. Thank you for the information.
